### PR TITLE
Document deployment and other common tasks

### LINKED ISSUE #5: Describe deployment and update workflow
We've settled on Docker images and docker-compose for deployment.
Now how will we deploy this, and how will updates happen? (Preferably without downtime.) Both of Foodsoft, sharedlists and services like MySQL, Redis and Postfix. How will configuration updates happen? How are old image versions being cleaned up?
This needs to be figured out and documented, so that the whole team can do this. Some discussion on the mailing list would be useful so that everyone is on board.

### PR DESCRIPTION
**Pull request by wvengen**
Fixes #5. Depends on #24.
Please look only at the last commit.

I didn't test this on a production server yet, of course. If issues arise, I'd be happy to update this.

### CODE REVIEW

**Comment by paroga** [comment]
sorry for responding so late: i looked over it already a few days ago and wan't 100% happy with it, but had no better idea. but it came up in the meantime:
1) what's the deal with the CERTBOT_ENABLE=0 default value? IMHO testing should be the exception an not production. (even enabling shouldn't do any harm and the setup works anyway)
2) I see problems when pushing to `production` with user `git`. I don't like to setup the virtual `git` user stuff to allow different people to push to that repo, since I'd like to get the host as simple as possible. The alternative of adding the whole `sudo` stuff sounds also more complicated then needed to me. What about installing the following pseudo-script (globally) instead :
```
mkdir tempdir && cd tempdir
git clone github.com/foodcoops/foodcoops.net && cd foodcoops.net
# TODO: verify GPG signed commit
cp /some/path/to/our-env ./.env
docker-compose pull
docker-compose build --pull
docker-compose up -d
```

This script can then be run via `ssh foodcoops.net /path/to/script` and `crond` and also avoids possible problems with the post-commit-hook since it's much much simpler and we do not have two (possible different) repositories. We could also let the script run via a GitHub webhook at a later time, when we verify the git commits via GPG.

**Comment by wvengen** [comment]
@paroga my reasoning with `CERTBOT_ENABLE` was that (1) in most cases, developers will check out the repo, modify it, and test it, so by default not breaking that when there is no fqdn reachable by certbot may be nice; and (2) this only needs to be set once for a production deployment as environment variable, bringing up the instances the first time one may find that the webserver setup or dns is not working properly yet, making it easy to get blacklisted for a short while by letsencrypt, this avoids that by making it a conscious step after all is done.

Nevertheless, I can see this can be quite confusing. Feel free to change what's necessary - I'm a bit busy in the coming days.

**Comment by wvengen** [comment]
Regarding (2), I've found very often that I'm doing a configuration change, and then sending a foodcoop a mail that something is changed/fixed. Having to wait for the cronjob would not be nice there.
I do like the idea of the git repository, since one already is pushing to the github repository, and a similar thing then is used to deploy. Also, this would be a good method to do auto-deploy at some point.

We could also make the repository pushable by our existing users, I didn't get around to testing that with permissions and such, that's why I opted for this. Same happens when we'd do something else than git.

**Comment by paroga** [comment]
ad 1) i don't see that a lot of people will play around with this repository and when they do, they might have already a FQDN. I'd prefer `CERTBOT_ENABLE` to be enabled by default, if you're ok with that.

ad2) There is no reason for the cron job! You will just run that script via `ssh our-server /path/to/script` when you want an instant update! The only difference is that you must push to GithHub first (which should be done anyway IMHO) and then run the script instead of pushing to a second repository. We can trigger this script later via a GitHub-webhook (when we sign our commits via GPG) also, so there is no need for a second push.

**Comment by wvengen** [comment]
ad 1) fine, let's document in the README to start with it disabled, so that when testing locally, it defaults to something that works locally.

ad 2) also sounds good! (could even put in or symlink to /usr/local/bin/ for ease of use). We do need a cronjob for base image updates, right?

**Pull request merged**
